### ISSUE TITLE
incompatibility with Forge essentials

### ISSUE THREAD

**Issue by darkcamo12** [GoryMoon/Chargers#3]
Minecraft: 1.12.2
Forge: 1.12.2-14.23.5.2838
Chargers: 1.12.2-1.2.0.4
Forge essentials: 1.12.2-12.3.58

so i added forge essentials to a mod pack running Chargers version 1.2.0.4 once i done that i get the following error

https://pastebin.com/iNGN7WMi

**Comment by tuxokc** [comment]
Here is a note on what one is not supposed to do with I18N on the server side:

https://mcforge.readthedocs.io/en/latest/concepts/internationalization/#netminecraftclientresourcesi18n-client-only


I think the fix is as simple as putting "@SideOnly(Side.CLIENT)" above the offending statement.  

https://pastebin.com/QWjVMsHG

I have tested this with SevTech Ages 3.1.2 Hotfix 1, and it works for me!

**Comment by GoryMoon** [comment]
Sorry for missing this for so long, for some reason I wasn't watching the repo so I did get notified about the issues.
A new version is available now.
